PreCommit:
  LineLength:
    enabled: true
    description: Verify source lines do not exceed 72 columns
    max: 72
    exclude: [
      "__tests__/**/*.xml",
      "__tests__/**/*.srt"
    ]
  Standard:
    enabled: true
    required_executable: "node_modules/.bin/standard"
    command: ["node_modules/.bin/standard"]
